baseURL = "https://hyunyoung2.github.io/customizing-version-hugo-example/"
languageCode = "en-us"
title = "The customized version of hugo example"


theme = "docdock"
themeDir = "themes"
publishDir = "docs"
